[package]
name = "nop-rt-tls"
version = "0.1.29"
edition = "2024"

[dependencies]
arc-swap = "1.8.2"
async-trait = "0.1.89"
base64 = "0.22"
hex = "0.4"
hickory-resolver = "0.26.1"
log = "0.4.29"
nop-config = { path = "../nop-config" }
nop-rt-paths = { path = "../nop-rt-paths" }
rcgen = "0.14.7"
reqwest = { version = "0.13.1", default-features = false, features = ["json", "query", "rustls-no-provider"] }
ring = "0.17"
rustls = { version = "0.23.36", default-features = false, features = ["ring", "std"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
serde_yaml = "0.9"
sha2 = "0.11"
time = "0.3.46"
tokio = { version = "1.49.0", features = ["full"] }
x509-parser = "0.18.0"

[dev-dependencies]
nop-config = { path = "../nop-config", features = ["test-helpers"] }
nop-testing = { path = "../nop-testing" }
