[package]
name = "nop-admin"
version = "0.1.29"
edition = "2024"

[dependencies]
actix-web = { version = "4.12.1", features = ["rustls-0_23"] }
actix-ws = "0.4.0"
futures-util = "0.3"
log = "0.4.29"
nop-config = { path = "../nop-config" }
nop-library = { path = "../nop-library" }
nop-management-bus = { path = "../nop-management-bus" }
nop-management-contract = { path = "../nop-management-contract" }
nop-rt-bootstrap = { path = "../nop-rt-bootstrap" }
nop-rt-csrf = { path = "../nop-rt-csrf" }
nop-rt-headers = { path = "../nop-rt-headers" }
nop-rt-iam = { path = "../nop-rt-iam" }
nop-rt-paths = { path = "../nop-rt-paths" }
nop-rt-release = { path = "../nop-rt-release" }
nop-rt-security = { path = "../nop-rt-security" }
nop-rt-templates = { path = "../nop-rt-templates" }
nop-security-paths = { path = "../nop-security-paths" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["full"] }
urlencoding = "2.1"
uuid = { version = "1.20.0", features = ["v4"] }

[dev-dependencies]
awc = { version = "3.8.1", default-features = false, features = ["cookies", "compress-gzip", "rustls-0_23-webpki-roots"] }
futures-util = { version = "0.3", features = ["sink"] }
nop-testing = { path = "../nop-testing" }
rustls = { version = "0.23.36", default-features = false, features = ["ring", "std"] }
tempfile = "3.24.0"
