[package]
name = "nop-rt-iam"
version = "0.1.29"
edition = "2024"

[dependencies]
actix-web = { version = "4.12.1", features = ["rustls-0_23"] }
argon2 = "0.5"
base64 = "0.22"
chrono = { version = "0.4.43", features = ["serde"] }
hmac = "0.13"
log = "0.4.29"
nop-config = { path = "../nop-config" }
nop-iam-passwords = { path = "../nop-iam-passwords" }
nop-library = { path = "../nop-library" }
nop-roles = { path = "../nop-roles" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.149"
serde_yaml = "0.9"
sha2 = "0.11"
tokio = { version = "1.49.0", features = ["full"] }
uuid = { version = "1.20.0", features = ["v4", "serde"] }

[dev-dependencies]
actix-http = "3.11.2"
nop-testing = { path = "../nop-testing" }
tempfile = "3.24.0"
